name: Update File

on:
  push:
    branches:
      - main # change this to your default branch

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
           ref: argocd
      - run: sed -i 's#harshakp06/numeric-app:.*#harshakp06/numeric-app:${{ github.sha }}#g' argocd/k8s_deployment_service.yaml
      - uses: wow-actions/update-file@v1.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: argocd/k8s_deployment_service.yaml
          commit_message: 'docker image update'


