name: Update File

on:
  push:
    branches:
      - main # change this to your default branch

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           ref: argocd
      - uses: wow-actions/update-file@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: sed -i 's#replace#harshakp06/numeric-app:${GIT_COMMIT}#g' argocd/k8s_deployment_service.yaml # change this to your file path
          content: 'docker image change' # change this to your file content


